### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [SiarheiFedartsou/MeasurementTextField#1]
Hey @SiarheiFedartsou, your lib is really interesting, but it needs a README with more information. Please add example code so your users can learn about your library before even downloading anything. [You can use this as an example](https://github.com/goktugyil/EZSwiftExtensions).

Please fix this before we can approve [your PR in AwesomeiOS](https://github.com/vsouza/awesome-ios/pull/2218)

**Comment by SiarheiFedartsou** [comment]
[Done!](https://github.com/SiarheiFedartsou/MeasurementTextField/blob/master/README.md)
